---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  replicas: 1
  template:
    
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      hostNetwork: true
      nodeSelector:
         eks.amazonaws.com/nodegroup: br-mng-v1-1   
      containers:
      #- image: nginx
      - image: netshoot
        securityContext:
          privileged: true      
        imagePullPolicy: Always
        name: nginx
        #ports:
        #- name: http
          #containerPort: 80
      
---
