---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: validate
  replicas: 1
  template:
    
    metadata:
      labels:
        app.kubernetes.io/name: validate
    spec:
      hostNetwork: true
      nodeSelector:
         eks.amazonaws.com/nodegroup: br-mng-v1-1   
      containers:
      - image: 000474600478.dkr.ecr.us-east-1.amazonaws.com/bottlerocket-cis-validating-image
        #command: ["/bin/bash", "sleep", "10000"]
        securityContext:
          privileged: true      
        imagePullPolicy: Always
        name: validate
      
---
