---
apiVersion: batch/v1
kind: Job
metadata:
  name: eks-cis-benchmark
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      hostPID: true
      nodeSelector:
         eks.amazonaws.com/nodegroup: bottlerocket-mng2      
      containers:
        - name: eks-cis-benchmark
<<<<<<< HEAD
          image: 000474600478.dkr.ecr.us-east-1.amazonaws.com/bottlerocket-cis-validating-image
          imagePullPolicy: Always
=======
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$VALIDATION_ECR_REPO
>>>>>>> 5b92aafb9d9559e5e6c6260765de55e52afcbdb4
          securityContext:
            privileged: true
      restartPolicy: Never
