---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  replicas: 1
  template:
    
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      nodeSelector:
         eks.amazonaws.com/nodegroup: br-mng-v1-1   
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - name: http
          containerPort: 80
      
---
