apiVersion: v1
kind: Pod
metadata:
  name: validate-pod
spec:
  hostNetwork: true
  nodeSelector:
     eks.amazonaws.com/nodegroup: bottlerocket-mng2  
  containers:
  - name: validate-pod
    image: 000474600478.dkr.ecr.us-east-1.amazonaws.com/bottlerocket-cis-validating-image
    imagePullPolicy: Always
    securityContext:
      privileged: true
 
