apiVersion: v1
kind: Pod
metadata:
  name: validate-pod
spec:
  hostNetwork: true
  nodeSelector:
     eks.amazonaws.com/nodegroup: bottlerocket-mng2  
  containers:
  - name: validate-pod
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$VALIDATION_ECR_REPO
    imagePullPolicy: Always
    securityContext:
      privileged: true
 